name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: [ '5.5', '5.6', '5.7' ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build
        run: swift build

      - name: Test
        run: swift test
