name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: [ '6.0' ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Verify Swift Installation
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test
